apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommurz-app
  labels:
    app: ecommurz-app
spec:
  selector:
    matchLabels:
      app: ecommurz-app
  template:
    metadata:
      labels:
        app: ecommurz-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-ecommurzapp: "database/creds/ecommurz-db-readonly"
        vault.hashicorp.com/secret-volume-path-ecommurzapp: "/app/config"
        vault.hashicorp.com/agent-inject-file-ecommurzapp: "conf.yaml"
        vault.hashicorp.com/agent-inject-template-ecommurzapp: |
          {{- with secret "database/creds/ecommurz-db-readonly" -}}
          DB_HOST: ecommurz-db
          DB_PORT: 5432
          DB_USERNAME: {{ .Data.username }}
          DB_PASSWORD: {{ .Data.password }}
          DB_NAME: ecommurz-db
          {{- end }}
        vault.hashicorp.com/role: "ecommurz-app"
    spec:
      serviceAccountName: ecommurz-app
      containers:
      - name: ecommurz-app
        image: fadhilthomas/ecommurz-app:1.3
        ports:
        - name: http
          containerPort: 8090